articles/urls.py
from django.conf.urls import url, include
from . import views

# in app = articles
app_name ='articles' 
urlpatterns = [
    url(r'^$',                      views.articles_list,    name='articles_list'),
    url(r'^detail/(?P<pk>\d+)$',    views.article_detail,   name='article_detail'),
    url(r'^edit/(?P<pk>\d+)$',      views.article_edit,     name='article_edit'),
    #
    url(r'^create/',                views.create_article,   name='create_article')
]

mysite/articles/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.articles_list, name='articles_list'),
    url(r'^detail/(?P<pk>\d+)$', views.article_detail, name='article_detail'),
    url(r'^edit/(?P<pk>\d+)$', views.article_edit, name='article_edit'),
    url(r'^create', views.create_articles, name = 'create_articles'),
    url(r'^about/', views.about, name='about'),
    url(r'^delete/(?P<pk>\d+)$', views.delete, name='ad'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
#    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('articles.urls', namespace="articles"), name="articles"),
#    url(r'^$', views.homepage, name='home'),
#     url(r'^$', views.index, name='home'),
]

webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls', namespace="articles"), name="articles"),
]

articles/models.py
from django.db import models

# Create your models here.

class Articles(models.Model):

    title = models.CharField(max_length=255)
    description = models.TextField()
    author = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def is_updated(self):
        return self.created_at.strftime('%Y-%m-%d %H:%M:%S') != self.updated_at.strftime('%Y-%m-%d %H:%M:%S')
#
# Vote: 1,2,.. stars
class Vote(models.Model):
    text = models.CharField(    max_length=200)
    date = models.DateTimeField('date published')

#
class Choice(models.Model):
    question    = models.ForeignKey(    Vote, on_delete=models.CASCADE)
    text        = models.CharField(     max_length=200)
    votes       = models.IntegerField(  default=0)

mysite/articles/models.py
from django.db import models

# Create your models here.

class Articles(models.Model):

    title = models.CharField(max_length=255)
    description = models.TextField()
    author = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def is_updated(self):
        return self.created_at.strftime('%Y-%m-%d %H:%M:%S') != self.updated_at.strftime('%Y-%m-%d %H:%M:%S')

mysite/articles/forms.py
from django import forms

from .models import Articles

class PostForm(forms.ModelForm):

    class Meta:
        model = Articles
        fields = ('title', 'description','author')

articles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib import messages
from .models import Articles
from .forms import PostForm

# Create your views here.

def articles_list(request):
    articles_list = Articles.objects.all().order_by('created_at')
    context = {'articles': articles_list}
    return render(request, 'articles/ListArticles.html', context)

def article_detail(request, pk):
    article = Articles.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/DetailArticle.html', context)

def article_edit(request, pk):
    article = get_object_or_404(Articles, pk=pk)
    form = PostForm(request.POST, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.updated_at = timezone.now()
        article.save()
        message = "Article succesfully updated at " + article.updated_at.strftime('%Y-%m-%d %H:%M:%S')
        context = {"message": message , "form": form}
    else:
        form = PostForm(instance=article)
        context = {"message": "", "form": form}
    return render(request, 'articles/EditArticle.html', context)

# CREATE
def create_article(request):
    article = Articles()
    form = PostForm(request.POST, instance=article)
    if form.is_valid():
        article             = form.save(commit=False)
        article.created_at  = timezone.now()
        article.save()
        message             = "Article succesfully created at " + article.created_at.strftime('%Y-%m-%d %H:%M:%S')
        context = {"message": "", "form": form, "article": create_article}
    else:
        form = PostForm(instance=article)
        context = {"message": "", "form": form, "article": create_article}
    return render(request, 'articles/create_article.html', context)

mysite/articles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib import messages
from .models import Articles
from .forms import PostForm
from django.core.urlresolvers import reverse
# Create your views here.

def about(request):
    return render(request, 'articles/about.html')



def articles_list(request):
    articles_list = Articles.objects.all().order_by('created_at')
    context = {'articles': articles_list}
    return render(request, 'articles/ListArticles.html', context)

def article_detail(request, pk):
    article = Articles.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/blog.html', context)

#def article_detail(request, pk):
#    article = Articles.objects.get(pk=pk)
#    context = {'article': article}
#    return render(request, 'articles/DetailArticle.html', context)

def article_edit(request, pk):
    article = get_object_or_404(Articles, pk=pk)
    form = PostForm(request.POST, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.updated_at = timezone.now()
        article.save()
      #  message = "Article succesfully updated at " + article.updated_at.strftime('%Y-%m-%d %H:%M:%S')
       # context = {"message": message , "form": form}
        return redirect('articles:articles_list')
    else:
        form = PostForm(instance=article)
       # context = {"message": "", "form": form}
    return render(request, 'articles/EditArticle.html', context)

def delete(request, pk):
        article=get_object_or_404(Articles, pk=pk).delete()
       # return render(request, "articles/delete.html")
        return render(request,'articles/delete.html')

def create_articles(request):
   
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.published_date =timezone.now()
            article.save()
              
        return redirect('articles:articles_list')
    else:
        form = PostForm()
    return render(request, 'articles/createArticles.html', {'form': form})

articles/templates/articles/DetailArticle.html
{% extends 'articles/base.html' %}


{% block content %}
    <h2>{{ article.title }}</h2>
    <h5><span class="glyphicon glyphicon-time"></span> Post by {{ article.author }}, {{ article.created_at }}</h5>
    <p>{{ article.description}}</p>
    <br><br>
    <a href="{% url 'articles:article_edit' article.pk %}" class="btn btn-warning">Edit Article</a>
    <a href="#" class="btn btn-danger">Delete Article</a>
{% endblock %}

articles/templates/articles/ListArticles.html
{% extends 'articles/base.html' %}


{% block content %}
    {% for article in articles %}
      <h2>{{ article.title }}</h2>
      <h5><span class="glyphicon glyphicon-time"></span> Post by {{ article.author }}, Created at {{ article.created_at }}
      {% if article.is_updated %}
          Updated at {{ article.updated_at }}
      {% endif %}</h5>
      <p>{{ article.description|truncatechars:80}}</p>
      <a href="{% url 'articles:article_detail' article.pk %}">Read more</a>
      <br><br>
    {% endfor %}
{% endblock %}

articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block page_title %} Agility Factory {% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row">
      <div class="col-sm-12" style="height:100px; color:red; margin:10px; background-color:#eee;">
          <h2>Agility Factory - The super blog</h2>
      </div>
  </div>
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>Agility's Blog</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="{% url 'articles:articles_list' %}">Home</a></li>
        <li class="active"><a href="{% url 'articles:create_article' %}">Create Article</a></li>
      </ul><br>
    </div>

    <div class="col-sm-9">
       {% block content %}

      
      {% endblock %}
    </div>
  </div>
</div>


</body>
</html>

articles/templates/articles/create_article.html
{% extends 'articles/base.html' %}

{% block content %}
    <h1>Create post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {% for field in form %}
            <fieldset class="control-group">
                <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                <div class="controls">
                    {{ field }}
                </div>
            </fieldset>
        {% endfor %}
        <br><br>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    <h2>{{ message }}</h2>
{% endblock %}

mysite/articles/templates/articles/00-ListArticles.html
{% extends 'articles/base.html' %}




{% block content %}


             <section class="tm-section">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-xs-center">
                            <img src="../../../static/img/00-movie.jpg"                               
                            width="400"
                            height="340">
                        <h2 class="tm-gold-text tm-title">Introduction</h2>
                        <p class="tm-subtitle">In this website you can disccus and critisize the movies</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">

                    </div>
                </div> <!-- row -->



   {% for article in articles %}
      <h2>{{ article.title }}</h2>
      <h5><span class="glyphicon glyphicon-time"></span> Post by {{ article.author }}, Created at {{ article.created_at }}
      {% if article.is_updated %}
          Updated at {{ article.updated_at }}
      {% endif %}</h5>
      <p>{{ article.description|truncatechars:80}}</p>
      <a href="{% url 'articles:article_detail' article.pk %}">Read more</a>
      <br><br>
    {% endfor %}
{% endblock %}

mysite/articles/templates/articles/010-base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block page_title %} Agility Factory {% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row">
      <div class="col-sm-12" style="height:100px; color:red; margin:10px; background-color:#eee;">
      </div>
  </div>
      </ul><br>
    </div>

    <div class="col-sm-9">
       {% block content %}

      
      {% endblock %}
    </div>
  </div>
</div>


</body>
</html>

mysite/articles/templates/articles/02-base.html
{% load staticfiles %}  
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block page_title %} Blog Movies {% endblock %}</title>
<!--
Classic Template
http://www.templatemo.com/tm-488-classic
-->
    <!-- load stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="../../../static/css/bootstrap.min.css">                                      <!-- Bootstrap style -->
    <link rel="stylesheet" href="../../../static/css/templatemo-style.css">                                   <!-- Templatemo style -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
          <![endif]-->
</head>

    <body>
       
        <div class="tm-header">
            <div class="container-fluid">
                <div class="tm-header-inner">
                    <a href="#" class="navbar-brand tm-site-name">Movies BLog</a>
                    
                    <!-- navbar -->
                    <nav class="navbar tm-main-nav">

                        <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                            &#9776;
                        </button>
                        
                        <div class="collapse navbar-toggleable-sm" id="tmNavbar">
                            <ul class="nav navbar-nav">
                                <li class="nav-item active">
                                    <a href="#" class="nav-link">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">Blog</a>
                                </li>
                                
                                <li class="nav-item">
                                    <a href="#" class="nav-link">About</a>
                                </li>
                            </ul>                        
                        </div>
                        
                    </nav>  

                </div>                                  
            </div>            
        </div>

            <section class="tm-section">
            <div class="container-fluid">
                <div class="row">
                    </div>
{% block content %}

      
      {% endblock %}            

                </div>
            </div>
        </section>
        
        <footer class="tm-footer">
            <div class="container-fluid">
                <div class="row">
                    
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">
                        
                        <div class="tm-footer-content-box">
                            
                            
                        </div>
                                                
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">
                        <div class="tm-footer-content-box tm-footer-links-container">
                        </div>
                        
                    </div>

                    <!-- Add the extra clearfix for only the required viewport 
                        http://stackoverflow.com/questions/24590222/bootstrap-3-grid-with-different-height-in-each-item-is-it-solvable-using-only
                    -->
                    <div class="clearfix hidden-lg-up"></div>

                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">

                        <div class="tm-footer-content-box">
                        </div>
                        
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">

                        <div class="tm-footer-content-box">
                         </div>
                        
                    </div>


                </div>

                <div class="row">
                    <div class="col-xs-12 tm-copyright-col">
                        <p class="tm-copyright-text">Copyright 2018 pylinux</p>
                    </div>
                </div>
            </div>
        </footer>

        <!-- load JS files -->
        <script  src="../../../static/js/jquery-1.11.3.min.js"></script>             <!-- jQuery (https://jquery.com/download/) -->
        <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script> <!-- Tether for Bootstrap, http://stackoverflow.com/questions/34567939/how-to-fix-the-error-error-bootstrap-tooltips-require-tether-http-github-h --> 
        <script  src="../../../static/js/bootstrap.min.js"></script>                 <!-- Bootstrap (http://v4-alpha.getbootstrap.com/) -->
       
</body>
</html>

mysite/articles/templates/articles/DetailArticle.html
{% extends 'articles/base.html' %}


{% block content %}
    <h2>{{ article.title }}</h2>
    <h5><span class="glyphicon glyphicon-time"></span> Post by {{ article.author }}, {{ article.created_at }}</h5>
    <p>{{ article.description}}</p>
    <br><br>
    <a href="{% url 'articles:article_edit' article.pk %}" class="btn btn-warning">Edit Article</a>
    <a href="{% url 'articles:ad' article.pk %}" class="btn btn-warning"> delete Article</a>

{% endblock %}

mysite/articles/templates/articles/ListArticles.html
{% extends 'articles/base.html' %}

  
{% block content %}

<div class="tm-header">
                    <!-- navbar -->
<br> <br>  <br> <br>

                        <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                            &#9776;
                        </button>
                        
                        <div class="collapse navbar-toggleable-sm" >
                            <ul class="nav navbar-nav">
                                <li class="nav-item active">
                                    <a href="{%url 'articles:articles_list' %}" class="nav-link">Home-Blog</a>
                                </li>
                                
                                <li class="nav-item">
                                    <a href="{% url 'articles:about'%}" class="nav-link">About</a>
                                </li>
                            </ul>                        
                        </div>
                        
                    </nav>  

</div>



             <section class="tm-section">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-xs-center">
                            <img src="../../../static/img/00-movie.jpg"                               
                            width="400"
                            height="340">
                        <h2 class="tm-gold-text tm-title">Introduction</h2>
                        <p class="tm-subtitle">In this website you can disccus and critisize the movies</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">

                    </div>
                </div> <!-- row -->
         <div class="container-fluid">
    <div class="row content">
        <li class="active"> To create your post: <a href="{% url 'articles:create_articles' %}">Click here</a></li>
      </ul><br>
    </div 


   {% for article in articles %}
      <h2>{{ article.title }}</h2>
      <h5><span class="glyphicon glyphicon-time"></span> Post by {{ article.author }}, Created at {{ article.created_at }}
      {% if article.is_updated %}
          Updated at {{ article.updated_at }}
      {% endif %}</h5>
      <p>{{ article.description|truncatechars:80}}</p>
      <a href="{% url 'articles:article_detail' article.pk %}">Read more</a>
      <br><br>
    {% endfor %}
{% endblock %}

mysite/articles/templates/articles/about.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> About Page</title>
<!--
Classic Template
http://www.templatemo.com/tm-488-classic
-->
    <!-- load stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  <!-- Google web font "Open Sans" -->

    <link rel="stylesheet" href="../../../static/css/bootstrap.min.css">                                      <!-- Bootstrap style -->
    <link rel="stylesheet" href="../../../static/css/templatemo-style.css">                                   <!-- Templatemo style -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
          <![endif]-->
</head>

    <body>
       
        <div class="tm-header">
            <div class="container-fluid">
                <div class="tm-header-inner">
                    <a class="navbar-brand tm-site-name">About us</a>
                    
                    <!-- navbar -->
                    <nav class="navbar tm-main-nav">

                        <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                            &#9776;
                        </button>
                        
                        <div class="collapse navbar-toggleable-sm" id="tmNavbar">
                            <ul class="nav navbar-nav">
                                <li class="nav-item">
                                    <a href="{%url 'articles:articles_list' %}" class="nav-link">Home-Blog</a>
                                </li>
                                <li class="nav-item active">
                                        <a href="{% url 'articles:about'%}"  class="nav-link">About</a>  
                                </li>
                                </ul>                        
                        </div>
                        
                    </nav>  

                </div>                                  
            </div>            
        </div>

        <div class="tm-about-img-container">
            
        </div>

        <section class="tm-section">
            <div class="container-fluid">
                <div class="row tm-2-rows-sm-swap">
                      <div class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-xl-9 tm-2-rows-sm-down-1">
                        <h3 class="tm-gold-text">How we are?</h3>
                        <p>Gabriel Cordier and Zakaria Alamiddine are memebers from AgilityFactory, aiming to learn python</p>
                        </div>
                </div>
                
                <div class="row tm-margin-t-mid">
               
                </div>

                <div class="row tm-margin-t-mid">
                   
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                      
                    </div>

                </div>

                <div class="row tm-margin-t-mid">
                    <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">

                       

                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">

                       
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">

                       

                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">                                         

                    </div>
                </div> <!-- row -->

            </div>
        </section>

      
          
        <footer class="tm-footer">
            <div class="container-fluid">
                <div class="row">
                    
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">
                        
                        <div class="tm-footer-content-box">
                            <h3 class="tm-gold-text tm-title tm-footer-content-box-title">Follow us on Github:</h3>

 <img  src="../../../static/img/github.svg" alt="Image" class="tm-margin-b-20 img-fluid">   
                           
                        </div>
                                                
                    </div>

                    </div>

                    <!-- Add the extra clearfix for only the required viewport 
                        http://stackoverflow.com/questions/24590222/bootstrap-3-grid-with-different-height-in-each-item-is-it-solvable-using-only
                    -->
                    <div class="clearfix hidden-lg-up"></div>

                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">
  <h4 class="tm-margin-b-20">  <a href="https://github.com/gitcordier" class="tm-margin-b-30"> Gabriel Cordier</a></h4>

<h4 class="tm-margin-b-20"> <a href="https://github.com/lezakaria" class="tm-margin-b-30"> Zakaria Alamiddine</a></h4>
                        
                    </div>
                    

                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">

                        <div class="tm-footer-content-box">
                        
                           <div class="tm-margin-b-30">
                                
                            </div>
                            

                        </div>
                        
                    </div>


                </div>

                <div class="row">
                    <div class="col-xs-12 tm-copyright-col">
                        <p class="tm-copyright-text">Copyright 2018 Pylinux</p>
                    </div>
                </div>
            </div>
        </footer>

        <!-- load JS files -->
        <script src="js/jquery-1.11.3.min.js"></script>             <!-- jQuery (https://jquery.com/download/) -->
        <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script> <!-- Tether for Bootstrap, http://stackoverflow.com/questions/34567939/how-to-fix-the-error-error-bootstrap-tooltips-require-tether-http-github-h --> 
        <script src="js/bootstrap.min.js"></script>                 <!-- Bootstrap (http://v4-alpha.getbootstrap.com/) -->
       
</body>
</html>

mysite/articles/templates/articles/blog.html
{% extends 'articles/base.html' %}

  
{% block content %}

<div class="tm-header">
                    <!-- navbar -->
<br> <br>  <br> <br>


                        <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                            &#9776;
                        </button>
                        
                        <div class="collapse navbar-toggleable-sm" >
                            <ul class="nav navbar-nav">
                                <li class="nav-item ">
                                    <a href="{%url 'articles:articles_list' %}" class="nav-link">Home-Blog</a>
                                </li>
                                <li class="nav-item active">
                                    <a  class="nav-link">Blog-edit</a>
                                </li>
                                
                                <li class="nav-item">
                                    <a href="{% url 'articles:about'%}"  class="nav-link">About</a>
                                </li>
                            </ul>                        
                        </div>
                        
                    </nav>  

</div>
<div class="container">
                <img  src="../../../static/img/cast.png" alt="Image" class="tm-margin-b-20 img-fluid">
        </div>



             <section class="tm-section">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-xs-center">
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">

                    </div>
                </div> <!-- row -->



    <h2>{{ article.title }}</h2>
    <h5><span class="glyphicon glyphicon-time"></span> Post by {{ article.author }}, {{ article.created_at }}</h5>
    <p>{{ article.description}}</p>
    <br><br>
    <a href="{% url 'articles:article_edit' article.pk %}" class="btn btn-warning">Edit Article</a>
    <a href="{% url 'articles:ad' article.pk %}" class="btn btn-warning"> delete Article</a>

{% endblock %}

mysite/articles/templates/articles/createArticles.html
{% extends 'articles/base.html' %}


{% block content %}
       <br> <br>  <br> <br>
    <h2> Create your article! </h2>  
    <br></br>
    <div class="container">
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</div>
{% endblock %}

mysite/articles/templates/articles/delete.html
{% extends 'articles/base.html' %}


{% block content %}
<div class="tm-header">
                    <!-- navbar -->
<br> <br>  <br> <br>


                        <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                            &#9776;
                        </button>
                        
                        <div class="collapse navbar-toggleable-sm" >
                            <ul class="nav navbar-nav">
                                <li class="nav-item ">
                                    <a href="{%url 'articles:articles_list' %}" class="nav-link">Home-Blog</a>
                                </li>
                                <li class="nav-item active">
                                    <a  class="nav-link">Blog-edit</a>
                                </li>
                                
                                <li class="nav-item">
                                    <a href="{% url 'articles:about'%}"  class="nav-link">About</a>
                                </li>
                            </ul>                        
                        </div>
                        
                    </nav>  

</div>
<br> <br>  <br> <br><br> <br>  <br> <br>
    <h2> Your post is deleted </h2>
{% endblock %}